import {
  Home, Users, Calendar, Building2, BookOpen, Ticket, Newspaper,
} from 'lucide-react'

// Unified Atletico palette — all cards share the red/dark theme,
// differentiated only by shade and accent intensity
export const SECTIONS = [
  {
    id: 'home', label: 'Home', sub: 'Welcome', stat: 'VFC',
    grad: 'from-[#CE1126] to-[#8B0000]',
    shadow: 'shadow-red-700/40',
    glow: 'rgba(206,17,38,0.30)',
    fg: '#ffffff', Icon: Home,
    rotY: -38, tz: -80,
    desc: 'Built on fire. Driven by hunger. Thirty years written in sweat, glory, and an unbreakable will to win.',
  },
  {
    id: 'squad', label: 'Squad', sub: '28 Players', stat: '28',
    grad: 'from-[#1a0a0e] to-[#CE1126]',
    shadow: 'shadow-red-900/40',
    glow: 'rgba(206,17,38,0.22)',
    fg: '#ffffff', Icon: Users,
    rotY: -22, tz: -20,
    desc: '28 world-class players, one unstoppable squad. Get to know every player who wears the Vortex crest.',
  },
  {
    id: 'matches', label: 'Matches', sub: 'Season 25/26', stat: '38',
    grad: 'from-[#8B0000] to-[#CE1126]',
    shadow: 'shadow-red-800/40',
    glow: 'rgba(139,0,0,0.30)',
    fg: '#ffffff', Icon: Calendar,
    rotY: -9, tz: 15,
    desc: 'Full fixture list, live scores, and match reports for every game of the 2025/26 season.',
  },
  {
    id: 'stadium', label: 'Stadium', sub: 'Vortex Arena', stat: '87K',
    grad: 'from-[#0a0008] to-[#7a0000]',
    shadow: 'shadow-red-950/40',
    glow: 'rgba(206,17,38,0.20)',
    fg: '#ffffff', Icon: Building2,
    rotY: 0, tz: 28,
    desc: 'Vortex Arena — 87,000 seats of pure noise. Book your place and feel the ground shake on match day.',
  },
  {
    id: 'history', label: 'History', sub: 'Est. 1994', stat: '43',
    grad: 'from-[#CE1126] to-[#4a0008]',
    shadow: 'shadow-red-700/40',
    glow: 'rgba(206,17,38,0.28)',
    fg: '#ffffff', Icon: BookOpen,
    rotY: 9, tz: 15,
    desc: '43 league titles. 18 European trophies. One club that never stopped chasing greatness since 1994.',
  },
  {
    id: 'tickets', label: 'Tickets', sub: 'Book Now', stat: '£29',
    grad: 'from-[#6b0010] to-[#CE1126]',
    shadow: 'shadow-red-800/40',
    glow: 'rgba(206,17,38,0.25)',
    fg: '#ffffff', Icon: Ticket,
    rotY: 22, tz: -20,
    desc: 'Season passes, match day tickets, and hospitality packages starting from £29. Sell out fast.',
  },
  {
    id: 'news', label: 'News', sub: 'Latest Updates', stat: '24/7',
    grad: 'from-[#1a0005] to-[#8B0000]',
    shadow: 'shadow-red-900/40',
    glow: 'rgba(139,0,0,0.28)',
    fg: '#ffffff', Icon: Newspaper,
    rotY: 38, tz: -80,
    desc: 'Transfer news, press conferences, injury updates, and match analysis — updated around the clock.',
  },
]
